server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system-template?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: 你的数据库用户名
    password: 你的数据库密码
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可以用的查询语句
      connection-test-query: SELECT 1

  servlet:
    multipart:
      # 单个上传文件的大小
      max-file-size: 50MB
      # 请求的大小
      max-request-size: 50MB

  # redis配置
  redis:
    # 超时时间
    connect-timeout: 10000ms
    # 服务器地址
    host: 你的redis地址
    # 端口号
    port: 6379
    # 数据库
    database: 2
    # 密码
    # password: 本地暂时没有配置密码，如果你的redis配置了密码则打开当前注释并输入密码
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 1024
        # 最大等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

# Mybatis-plus配置
mybatis-plus:
  # mapper配置文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型的别名（默认别名为类名）
  type-aliases-package: com.zrkizzy.template.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

# mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.zrkizzy.template.mapper: debug

# Jwt配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的秘钥
  secret: system-secret
  # JWT的超期限时间（60 * 60 * 24）24小时失效
  expiration: 604800
  # JWT负载中拿到的开头
  tokenHead: Bearer

# 文件上传配置
file:
  # 例如 /Users/zhangrongkang/workspace/MyProject/system-template/system-springboot/upload/ 最后的"/"不要省略
  path: 你的文件存储路径（到当前项目的upload文件下）
